<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright  Copyright (c)  2023.  Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

/** @var \Magento\Framework\Escaper $escaper */

?>

<small class="copyright">
    <h2><?= $escaper->escapeHtml(__('message.phtml: This footer message is pretty cool, huh?')) ?></h2>
    <?= $block->getChildHtml('sample_child') ?>
</small>
