<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
?>
<div data-mage-init='{"theme/hello":<?= $block->getJsLayout('title'); ?>}'>
    <small class="copyright">
        <h3><?= $escaper->escapeHtml(__('message_child.phtml: That\'s correct my good sir')) ?></h3>
        <h4><?= $block->escapeHtml(__('message_child.phtml: ') . $block->getData('title')); ?></h4>
    </small>
</div>
<textarea
    name="comment"
    id="comment"
    title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
    class="input-text"
    data-mage-init='{"Magento_Theme/js/validation": {"maxlen":"20","messagebox":"charNum"}}'
></textarea>
<span id="charNum"></span>
