<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright  Copyright (c)  2023.  Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div>
    <?php if ($block->getData('path_image')): ?>
        <div>
            <?php if ($block->getData('title')): ?>
                <h2><?= $block->escapeHtml($block->getData('title')); ?></h2>
            <?php endif;?>
        </div>
        <div>
            <img src="<?= $block->escapeUrl($block->getViewFileUrl($block->getData('path_image'))); ?>"
                 alt="<?= $block->escapeHtmlAttr($block->getData('title')); ?>" />
        </div>
    <?php endif; ?>
</div>
